
services:
  nginx:
    container_name: wfinstances-browser-nginx
    depends_on:
      - ui
    build:
      context: ./nginx
      args:
        PORT: 80
        SERVER_NAME: localhost
    secrets:
      - nginx_certificate
      - nginx_private_key
    ports:
      - 80:80
    networks:
      - nginx-network

  ui:
    container_name: wfinstances-browser-ui
    build: ./ui
    depends_on:
      - api
    environment:
      - PORT=8080
      - API_BASE_URL=http://api:8081
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - nginx-network

  api:
    container_name: wfinstances-browser-api
    build: ./api
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/?retryWrites=true&w=majority
    ports:
      - 127.0.0.1:8081:8081
    networks:
      - nginx-network

  mongodb:
    container_name: wfinstances-browser-mongodb
    image: mongo:5.0.26
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: wf_instance_browser_db
    volumes:
      - ~/mongodata:/data/db
    networks:
      - nginx-network

secrets:
  nginx_certificate:
    file: ~/WRENCH/WFCOMMONS/wfinstances-browser/nginx/cert.pem
  nginx_private_key:
    file: ~/WRENCH/WFCOMMONS/wfinstances-browser/nginx/privkey_no_pass.pem

volumes:
  db:

networks:
  nginx-network:
    name: nginx-network
    driver: bridge

