services:

  nginx:
    container_name: wfinstances-browser-nginx
    build: ./nginx
    depends_on:
      - ui
      - stupid_app
    ports:
      - 80:80
    networks:
      - nginx-network


  stupid_app:
    container_name: stupid_app
    build: stupid_app
    ports:
      - 3000:3000
    networks:
      - nginx-network

  ui:
    container_name: wfinstances-browser-ui
    build: ./ui
    depends_on:
      - api
    environment:
      - PORT=8080
      - API_BASE_URL=http://api:8081
    ports:
      - 8080:8080
    networks:
      - nginx-network

  api:
    container_name: wfinstances-browser-api
    build: ./api
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/?retryWrites=true&w=majority
    ports:
      - 8081:8081
    networks:
      - nginx-network

  mongodb:
    container_name: wfinstances-browser-mongodb
    image: mongo:5.0.26
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: wf_instance_browser_db
    volumes:
      - db:/data/db
    networks:
      - nginx-network


volumes:
  db:

networks:
  nginx-network:
    name: nginx-network
    driver: bridge

